name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  print-env-vars:
    runs-on: ubuntu-latest
    steps:
      - run: env
  print-secrets:
    runs-on: ubuntu-latest
    environment: default
    env:
      SECRET_ONE: ${{ secrets.TEST_SECRET_1 }}
      SECRET_TWO: ${{ secrets.SECRET_TEST_2 }}
      SECRET_THREE: ${{ secrets.TEST_SCRET_3 }}
    steps:
      - run: env | grep SECRET
      - run: echo "test secret one passes check"
        if: env.TEST_SECRET_1 == 'ts1reporting'
